- project:
    name: 'BDD_create_new_slave'
    controlled-branches-regex: '^\w+$'
    branch-strategy: 'feature-branches'
    pipeline-build-name: 'build'
    jobs-path: 'cd/jobs'
    jenkins:
      node: 'master'
      slaves:
        - unix-slave:
            name: 'test_slave'
            description: 'slave_1'
            executors: 3
            remote-root: '/fmsdcd/helloworld_slave1'
            labels: '{project.name}'
            host: 'localhost'
            port: '22'
            credentials:
                description: 'sabredev'
                username: 'sabredev'
                password: 'sabredev123'
            jvm-options: ''
            java-path: '/usr/java/jdk1.7.0_25/bin/java'
      node: 'master'
    repository:
      git-data:
        url: 'ssh://git@stash/cd/BDD_create_new_slave.git'
