- project:
    name: 'feature_branch_test'
    controlled-branches-regex: '^$'
    branch-strategy: 'feature-branches'
    pipeline-build-name: 'build'
    jobs-path: 'cd/jobs'

    jenkins:
      node: 'master'
    repository:
      git-data:
        url: 'ssh://git@stash/cd/feature_branch_test.git'

    job-groups:
        master_jobs: 'master|hotfix-*'
        feature_jobs: 'SFS-*'
        whatever_jobs: 'SCORE-*'
