- project:
    name: 'MAVEN-ENFORCER-RULES'
    all-branches-regex: 'master|SABRE-*|hotfix-*'
    branch-strategy: 'feature-branches'
    pipeline-build-name: '1-BUILD'
    jobs-path: 'cd'
    jenkins:
       node: 'master'
    repository:
       git-data:
          url: 'ssh://git@stash.uk.standardchartered.com:7999/ctxmvn/maven-enforcer-rules.git'
    jdk_version: 'JDK_1.7.0_25'
    maven_version: 'Maven 3.3.3'
    recipients: 'jacob.pezaro@sc.com'