---
svn:
  # url: http://10.21.151.130/svn/sabresrv/branches/sabre_r1.0_pd/SABRE
  # tag_url: http://10.21.151.130/svn/sabresrv/tags/
  url: http://10.128.77.82/svn/sabresrv/branches/sabre_r1.0_pd/SABRE
  tag_url: http://10.128.77.82/svn/sabresrv/tags/
  # username: 'bankid'
  # password: 'bankid_password'
mapping:
  CRT: 'CRT'
  SDF-APPS: 'SDF-APPS'
dod:
  base_url: 'http://scm.global.standardchartered.com/scm/page'
  # approver: 'Janefer Yamat'
  # approver: 'Ganesh Venkataraman'
  approver: 'Tarique Anwar'
  # approver: 'sbhat'
  submitter_email: 'aleksey.maksimov@sc.com'
  cc_email: 'SABREPSS@sc.com'
  vobname: '/vobs/sabresrv'
  viewname: 'sabre_r1.0_pd'
  jobname: 'sabre_r1.0_pd'
# Phases are: 04 > ST, 03 > OAT, 02 > UAT, 01 > SIT,
#             09 > Retrofit only for PRD, 08 > AIG_ASRM, 07 > PRD,
#             06 > RETROFIT, 05 > DR
# DOD for Variance MUST be filled with UAT phase
  phase: '07'
# SCM Severity
# 3 - EXCEPTION, 2 - Standard, 1 - EMERGENCY
  severity: '2'
  # username: 'bankid'
  # password: 'bankid_password'

redis:
  redis_scm_key: 'SCM_WEBHOOK_TRANSITIONS'
  scm_data:
    DOD: null
    CR: null
    Version: null
    binaries: null
