- bootstrap-base:
    name: 'bootstrap'
    # This is git object used by CD automation
    # Automation is going to instantiate GitData data object
    # as a holder of this information
    #
    # The object discovery rules are:
    # - all '-' characters will be removed
    # - all words around '-' character will be capitalized
    # - if there is no '-' char. then word will be capitalized
    #
    # Example:
    # git-data - meta.py.data_object.GitData
    # jenkins - meta.py.data_object.Jenkins
    #
    # Currently only objects in meta/py/data_objects can be used
    project-config-path: 'bootstrap/meta/projects'
    bootstrap-log-file: '/sabrebuild/bootstrap_logs/index.html'
    bootstrap-git-data:
        url: ssh://git@stash/raz/bootstrap.git
        branch: 'develop'
    # This is Jenkins object, which will have default url
    # it can be overridden in environments

    project-template:
      all-branches-regex: '.*'
      controlled-branches-regex: '^[A-Z]*-\d{1,5}$'
      pipeline-build-name: '1-build'
      # Prefix for artefact name. Used to construct full artefact name
      # example: SCBsabreSidrDCServer-1.4-3_master_82b671c.noarch.rpm
      #     will be constructed like this:
      #     {project.artefact_prefix}-{project.component_version.full_version}.{project.artefact-suffix}
      artefact-prefix: 'not_set'
      artefact-suffix: 'not_set'
      # URL for artefacts in Nexus
      artefact-nexus-url: 'not_set'
      wait-for-jobs: true
      # build-on-jobs-change - if set to True project pipeline
      # will be executed even if only jobs.yaml have changed
      build-on-jobs-change: true
      jenkins:
        url: http://sabrebuild1.uk.standardchartered.com:8080/
        virtualenv-home: '/home/sabredev/virtualenv/jenkins'
        virtualenv-python-home: 'bootstrap/meta/py/lib/jenkins-job-builder'
        node: 'master'
        views:
          # Only one top view is supported
          jenkins-nested-view:
              name: '{project.name}'
              parent-path: ''
              views:
                  - jenkins-list-view:
                      name: '{project.name}-repository'
                      parent-path: ''
                      base-jobs-builder:
                          jobs-path: 'bootstrap/meta'
                          branch-regex: '{project.controlled_branches_regex}'
                  - jenkins-list-view:
                      name: '{project.name}-release'
                      parent-path: ''
                      base-jobs-builder:
                          jobs-path: 'bootstrap/meta/projects/BASE/release_jobs'
                          branch-regex: '{project.controlled_branches_regex}'
                  - jenkins-nested-view:
                      name: '{project.name}-branches'
                      parent-path: ''
                      views:
                          - jenkins-branches-list-views:
                              name: '{project.name}-develop'
                              parent-path: ''
                              project-jobs-builder:
                                  jobs-path: '{project.jobs_path}'
                                  branch-regex: '{project.all_branches_regex}'
                                  pipeline-build-name: '{project.pipeline_build_name}'
                                  use-shallow-clone: 'true'
      repository:
         git-data:
            url: None
      recipients: 'Hughes-Zhiwei.Lu@sc.com'

      component-version:
          maven-version-helper:
              pom_location: 'pom.xml'
              element: 'version'
          env-version-helper:
              variable: 'BUILD_NUMBER'
          epoch-version-helper:
              tz: 'UTC'
          # full version used to retrieve/upload rpm
          full-version: ''
          # release-version used to create rpm
          release-version: ''

      remedy-cr:
          jenkins-fields:
            - name: 'USERNAME'
              description: 'Bank Id for person submitting CR/DOD'
              default: ''
            - name: 'PASSWORD'
              description: 'Bank Id password'
              default: ''
            - name: 'COMPONENT_NAME'
              description: 'Component to be submitted'
              default: '{project.name}'
            - name: 'VERSION'
              description: 'Version of component to be released'
              default: '{project.component_version.full_version_string}'
            - name: 'URL'
              description: 'URL to get released binary'
              default: ''

    # Environments - just named buckets grouping overrides and objects
    environments:
        - env:
            name: razor
            # This is env. specific override for Jenkins object
            jenkins:
                url: http://sabrebuild1.uk.standardchartered.com:8080/
                user-name: 1466811
                user-token: cc17bc107d6e1ca2638058a0d7be38a4
            # Env. specific override for GitData
            bootstrap-git-data:
                branch: master
            repository:
              git-data:
                  master-repo: /shared/opt/jenkins-home/master-repos/{project.name}
        - env:
            name: aleksey
            # This is env. specific override for Jenkins object
            jenkins:
                url: http://sabrebuild1.uk.standardchartered.com:8180/
                user-name: maleksey
                user-token: 3d261f625cd6b0e5ed443aa36bf49ea7
            # Env. specific override for GitData
            bootstrap-git-data:
                branch: integration
            repository:
              git-data:
                  master-repo: ~/src/helloworld/
        - env:
            name: devlocal
            # This is env. specific override for Jenkins object
            jenkins:
                url: http://sabrebuild1.uk.standardchartered.com:8180/
                user-name: maleksey
                user-token: 3d261f625cd6b0e5ed443aa36bf49ea7
            # Env. specific override for GitData
            bootstrap-git-data:
                branch: integration
            repository:
              git-data:
                  master-repo: /shared/opt/jenkins-home/master-repos/{project.name}
        - env:
            name: prod-dev
            # This is env. specific override for Jenkins object
            jenkins:
                url: http://sabrebuild2.uk.standardchartered.com:8080/
                user-name: 1459847
                user-token: f51df6644d2a343e1dfc2487f64f6531
            # Env. specific override for GitData
            bootstrap-git-data:
                branch: integration
            repository:
              git-data:
                  master-repo: /fmsdcd/master-repos/{project.name}
        - env:
            name: dev
            jenkins:
                user-name: jenkins
                user-token: 452c271c582c3dc8925ae320459c64da
            bootstrap-git-data:
                branch: develop
        - env:
            name: sabredashboard
            # This is env. specific override for Jenkins object
            jenkins:
                url: http://sabredashboard.gdc.standardchartered.com:8078/jenkins
                user-name: 1459847
                user-token: 8db9173ee5d883b1133bc9cd99957f99
            # Env. specific override for GitData
            bootstrap-git-data:
                branch: SFS-415
            repository:
              git-data:
                  master-repo: /shared/opt/sab_repo/master-repos/{project.name}

# Resulting structure will look like this:
#
# project.git_data                          - instance of GitData
# project.jenkins                           - instance of Jenkins
# project.environments.devlocal             - instance of Environments
# project.environments.devlocal.jenkins     - instance of Jenkins, all data from project.jenkins is here
# project.environments.devlocal.git_data    - instance of GitData, all data from project.git_data is here
# project.environments.dev
# project.environments.dev.jenkins
# project.environments.dev.git-data
