- project:
    name: 'GENIECORE'
    branch-strategy: 'feature-branches'  # options: 'feature-branches', 'trunk-based', 'self-managed'(S2BX model) & 'feature-branches-stages' (MIG model)
    pipeline-build-name: '1-validate'
    jobs-path: 'cd/jobs'
    all-branches-regex : '^FTA-\d+$'
    controlled-branches-regex : '^rebase-from-my-cold-dead-fingers$'   # can I make this any clearer? No. Rebasing.
    jenkins:
      slaves:
        - unix-slave:
            name: 'test_slave'
            description: 'test_slave'
            executors: 3
            remote-root: '/fmsdcd/GENIECORE_slave1'
            labels: '{project.name}'
            host: 'localhost'
            port: '22'
            credentials:
                description: 'creds1'
                username: 'sabredev'
                password: 'sabredev123'
            jvm-options: ''
            java-path: '/usr/java/jdk1.7.0_25/bin/java'
      node: 'master'
    repository:
       git-data:
          url: 'ssh://git@stash/fmt/geniecore.git'
