- project:
    name: 'CORTEX-MAVEN-PLUGIN'
    description: 'Cortex Maven plugin library'
    repository:
       git-data:
          url: 'ssh://git@stash/ctxmvn/cortex-maven-plugin.git'

    # features-branches (auto-rebase) or trunk-based (no auto-rebase)
    branch-strategy: 'feature-branches'

    pipeline-build-name: '1-build'

    # Path where the jobs.yaml can be found in the repo
    jobs-path: 'cd'

    # If your jobs need to run on slave - uncomment this and change node name
    # jenkins:
    #   node: 'master'

    # Which branches you want to have in Jenkins
    all-branches-regex: 'master|SABRE-.*'

    job-groups:
       master_jobs: 'master'
       feature_jobs: 'SABRE-.*'

    # Which branches you want to rebase (a regex of 'none' means rebase 'none' branch.)
    controlled-branches-regex: 'none'

    recipients: 'stephen.matthew@sc.com'